services:
  - type: web
    name: f759
    env: ruby
    buildCommand: bundle install
    startCommand: bundle exec rails server
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: f759-db
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
    preDeployCommand: |
      bundle exec rails db:migrate
      bundle exec rails db:seed
