services:
  - type: web
    name: f759
    env: ruby
    plan: free
    buildCommand: bundle install
    startCommand: bundle exec rails server
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: f759-db
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
databases:
  - name: f759-db
